### ISSUE TITLE
Bootstrap the repo

### ISSUE THREAD

**Issue by ChunyiLyu** [syntasso/kratix-cli#2]
## Context

Initialise the cli repo, and set it up with CI and stuff. Implement the first `help` command; it should look like the following

```bash
$> kratix help
CLI tool for Kratix

Usage:
  kratix [flags]
  kratix [command]

Examples:
The first step to write your promise:
    kratix init promise postgresql --group myorg.com --kind database

Available Commands:
  help        Help about any command
  init        Initialize a new project
  version     Print the kratix version

Flags:
  -h, --help                     help for kratix

Use "kratix [command] --help" for more information about a command.
```

## Tasks:

- [x] Use [cobra](https://github.com/spf13/cobra) to init (following https://github.com/spf13/cobra-cli/blob/main/README.md).
- [x] Add first command to our CLI (`help`)
- [x] Circle CI running tests on every commit
- [x] Simple readme that covers how to run test, build, and install
